import test from 'node:test';
import assert from 'node:assert/strict';

import { MODULE_CATALOG, MODULE_CATALOG_KEYS } from '../src/catalog.js';
import { planAutomaticDepot } from '../src/autoDepot.js';
import { getModuleRecipe } from '../src/moduleRecipes.js';
import {
  MODULE_CONTRACT_ASSIGNMENTS,
  MODULE_CONTRACT_PROFILES,
  hasExplicitModuleContract,
  resolveModuleContract,
} from '../src/moduleContracts.js';
import { FEATURE_CONTRACTS, getFeatureContract } from '../src/featureContracts.js';

const REQUIRED_CONTRACT_SECTIONS = Object.freeze([
  'state',
  'appearance',
  'renderer',
  'runtime',
  'composition',
  'bom',
  'tests',
  'behavior',
]);

test('every catalog item has an explicit module contract assignment', () => {
  const missing = MODULE_CATALOG_KEYS.filter((moduleKey) => !hasExplicitModuleContract(moduleKey));
  const stale = Object.keys(MODULE_CONTRACT_ASSIGNMENTS).filter((moduleKey) => !MODULE_CATALOG[moduleKey]);

  assert.deepEqual(missing, [], `Catalog items missing module contract: ${missing.join(', ')}`);
  assert.deepEqual(stale, [], `Module contracts reference missing catalog items: ${stale.join(', ')}`);
});

test('every catalog module contract resolves all required policy sections', () => {
  for (const moduleKey of MODULE_CATALOG_KEYS) {
    const contract = resolveModuleContract(moduleKey);
    assert.ok(contract, `Module contract did not resolve: ${moduleKey}`);
    assert.ok(MODULE_CONTRACT_PROFILES[contract.profile], `Unknown profile for ${moduleKey}: ${contract.profile}`);

    for (const section of REQUIRED_CONTRACT_SECTIONS) {
      assert.ok(contract[section], `${moduleKey} contract is missing ${section}`);
    }

    assert.ok(contract.state.owner, `${moduleKey} state owner is missing`);
    assert.ok(contract.state.persistence, `${moduleKey} persistence policy is missing`);
    assert.ok(contract.appearance.color, `${moduleKey} color policy is missing`);
    assert.ok(contract.appearance.image, `${moduleKey} image policy is missing`);
    assert.ok(contract.renderer.mode, `${moduleKey} renderer policy is missing`);
    assert.ok(contract.runtime.mode, `${moduleKey} runtime policy is missing`);
    assert.ok(contract.composition.mode, `${moduleKey} composition policy is missing`);
    assert.ok(contract.bom.mode, `${moduleKey} BOM policy is missing`);
    assert.equal(contract.tests.contract, 'required', `${moduleKey} must require contract tests`);

    assert.ok(contract.behavior.placement, `${moduleKey} placement behavior is missing`);
    assert.ok(Number.isFinite(Number(contract.behavior.moveSnapCm)), `${moduleKey} move snap is missing`);
    assert.ok(Number.isFinite(Number(contract.behavior.rotationStepDeg)), `${moduleKey} rotation step is missing`);
    assert.ok(contract.behavior.collision, `${moduleKey} collision behavior is missing`);
  }
});

test('recipe-backed module contracts resolve an actual canonical recipe', () => {
  for (const moduleKey of MODULE_CATALOG_KEYS) {
    const contract = resolveModuleContract(moduleKey);
    if (contract?.bom?.mode !== 'recipe') continue;

    const descriptor = MODULE_CATALOG[moduleKey];
    const recipe = getModuleRecipe(descriptor.type, descriptor.widthCm, {
      shelfCount: descriptor.shelfCount,
      shape: descriptor.shape,
    });

    assert.ok(recipe, `${moduleKey} declares recipe BOM but no canonical recipe resolves`);
  }
});

test('non-catalog runtime modules can also have explicit contracts', () => {
  const contract = resolveModuleContract('illuminated-foam');
  assert.ok(contract);
  assert.equal(contract.catalogKey, null);
  assert.equal(contract.behavior.placement, 'wall-overlay');
  assert.equal(contract.appearance.image, 'required');
});

test('automatic depot feature contract matches the contents generated by the planner', () => {
  const contract = FEATURE_CONTRACTS.automaticDepot;
  assert.equal(getFeatureContract('automatic-depot'), contract);

  const plan = planAutomaticDepot({
    standType: 'island',
    standXCm: 600,
    standYCm: 500,
    sizeKey: '200x200',
    includeContents: true,
  });

  assert.equal(plan.ok, true);
  const generatedContentKinds = plan.specs
    .map((spec) => spec.kind)
    .filter((kind) => contract.creates.contentKinds.includes(kind))
    .sort();

  assert.deepEqual(generatedContentKinds, [...contract.creates.contentKinds].sort());
  assert.equal(contract.trigger.contentToggle, 'includeContents');
});
