const fs=require('fs');
const p='src/scene3d.js';
let s=fs.readFileSync(p,'utf8');
s=s.replace('      const raw = new THREE.Group();\n      let meshCount = 0;','      const raw = new THREE.Group();\n      const haloShapeGroup = new THREE.Group();\n      let meshCount = 0;');
s=s.replace('          raw.add(mesh);\n          meshCount += 1;','          raw.add(mesh);\n          const haloMesh = new THREE.Mesh(new THREE.ShapeGeometry(shape, 10), new THREE.MeshBasicMaterial({ color: 0xffffff, transparent: true, opacity: 1, depthWrite: false, toneMapped: false, blending: THREE.AdditiveBlending }));\n          haloShapeGroup.add(haloMesh);\n          meshCount += 1;');
const a=`      const lightCount = 5;\n      for (let i = 0; i < lightCount; i += 1) {\n        const t = lightCount === 1 ? 0.5 : i / (lightCount - 1);\n        const light = new THREE.PointLight(0xffffff, 1.8, 0.55, 2);\n        light.position.set((t - 0.5) * widthM * 0.82, 0, -wallGapM * 0.55);\n        visualRoot.add(light);\n      }`;
const b=`      const haloLayers = [\n        { scale: 1.018, opacity: 0.44, z: -Math.max(0.002, wallGapM * 0.28) },\n        { scale: 1.045, opacity: 0.22, z: -Math.max(0.003, wallGapM * 0.52) },\n        { scale: 1.085, opacity: 0.09, z: -Math.max(0.004, wallGapM * 0.78) },\n      ];\n      haloLayers.forEach((layer) => {\n        const halo = haloShapeGroup.clone(true);\n        halo.traverse((child) => { if (child.isMesh) { child.material = child.material.clone(); child.material.opacity = layer.opacity; } });\n        halo.scale.set(scale * layer.scale, -scale * layer.scale, 1);\n        halo.position.set(-center.x * scale * layer.scale, center.y * scale * layer.scale, layer.z);\n        visualRoot.add(halo);\n      });`;
if(!s.includes(a)) throw new Error('light block not found');
s=s.replace(a,b);
fs.writeFileSync(p,s);
