from pathlib import Path
p=Path('src/style.css')
s=p.read_text()
old='''.collapsible-panel {\n  display: block;\n  padding: 0;\n  overflow: hidden;\n}\n\n.panel-summary {\n  display: flex;\n  min-height: 48px;\n  align-items: center;\n  justify-content: space-between;\n  gap: 12px;\n  padding: 14px;\n  color: #222b3b;\n  font-size: 14px;\n  font-weight: 800;\n  cursor: pointer;\n  list-style: none;\n  user-select: none;\n}\n\n.panel-summary::-webkit-details-marker {\n  display: none;\n}\n\n.panel-summary:hover {\n  background: #f8fafc;\n}\n\n.panel-chevron {\n  width: 9px;\n  height: 9px;\n  flex: 0 0 auto;\n  border-right: 2px solid #7a8494;\n  border-bottom: 2px solid #7a8494;\n  transform: rotate(45deg) translate(-2px, -2px);\n  transition: transform 160ms ease;\n}\n\n.collapsible-panel[open] > .panel-summary .panel-chevron {\n  transform: rotate(225deg) translate(-1px, -1px);\n}\n\n.panel-card-content {\n  display: flex;\n  flex-direction: column;\n  gap: 9px;\n  padding: 0 14px 14px;\n}\n\n.collapsible-panel:not([open]) > .panel-card-content {\n  display: none;\n}\n\n.collapsible-panel[open] > .panel-summary {\n  padding-bottom: 10px;\n}\n'''
new='''.collapsible-panel {\n  display: flex;\n  flex-direction: column;\n  gap: 9px;\n}\n\n.panel-summary {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  gap: 12px;\n  margin: 0 0 2px;\n  padding: 0;\n  color: #222b3b;\n  font-size: 14px;\n  font-weight: 800;\n  cursor: pointer;\n  list-style: none;\n  user-select: none;\n}\n\n.panel-summary::-webkit-details-marker {\n  display: none;\n}\n\n.panel-chevron {\n  width: 8px;\n  height: 8px;\n  flex: 0 0 auto;\n  border-right: 2px solid #7a8494;\n  border-bottom: 2px solid #7a8494;\n  transform: rotate(45deg) translate(-1px, -1px);\n  transition: transform 160ms ease;\n}\n\n.collapsible-panel[open] > .panel-summary .panel-chevron {\n  transform: rotate(225deg) translate(-1px, -1px);\n}\n\n.panel-card-content {\n  display: flex;\n  flex-direction: column;\n  gap: 9px;\n  padding: 0;\n}\n\n.collapsible-panel:not([open]) > .panel-card-content {\n  display: none;\n}\n'''
if old not in s:
    raise SystemExit('target block not found')
p.write_text(s.replace(old,new))
# trigger
